version: '3'

networks:
  appnetwork:
    driver: bridge

volumes:
  cache:
    driver: local
  db-data:
    driver: local

services:
  app:
    build:
      context: .
    container_name: monkeygram
    networks:
      - appnetwork
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - '8080:8080'
    environment:
      - SPRING_DATA_MONGODB_URI=${MONGO_DB_URI}

  db:
    image: mongo:latest
    container_name: mongo
    networks:
      - appnetwork
    volumes:
      - ./src/main/resources/db-init:/docker-entrypoint-initdb.d
      - db-data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    ports:
      - '27017:27017'




