create
user kitty superuser;
alter
user kitty password 'purrr';
create
database cats with owner kitty;

create table "monkey_user"
(
    id       varchar(64) not null,
    username varchar(255) default 'noname monkey',
    nickname varchar(255)
);

create unique index user_id_uindex
    on "monkey_user" (id);


INSERT INTO public.monkey_user (id, username, nickname)
VALUES ('tom', 'Thomas C. Andersun', 'neoc@t');
INSERT INTO public.monkey_user (id, username, nickname)
VALUES ('grumpy', 'Альфред Хичкот', 'sca_a_a_ry');
INSERT INTO public.cat_user (id, username, nickname)
VALUES ('harambe', 'Basileus Felis F.', 'under_wood');

create table monkey_post
(
    id            int generated by default as identity primary key,
    author_id     varchar(64) not null,
    description   varchar(500),
    photo_url     varchar(1000),
    creation_date timestamp,
    CONSTRAINT fk_post_author
        FOREIGN KEY (author_id)
            REFERENCES monkey_user (id)
);
