-- step 0: connect to empty DB

--step 1: create table monkey_user, monkey_post, monkey_follow
create table monkey_user
(
    id       varchar(64) not null,
    username varchar(255) default 'noname monkey',
    nickname varchar(255)
);

create unique index user_id_uindex
    on "monkey_user" (id);

create table monkey_post
(
    id            int generated by default as identity primary key,
    author_id     varchar(64) not null,
    description   varchar(500),
    photo_url     varchar(1000),
    creation_date timestamp,
    CONSTRAINT fk_post_author
        FOREIGN KEY (author_id)
            REFERENCES monkey_user (id)
);

create table monkey_follow
(
    id            int generated by default as identity primary key,
    author_id     varchar(64) references monkey_user(id),
    follower_id   varchar(64) references monkey_user(id)

);
